[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pysoar"
dynamic = ["version"]
description = 'Implementation of the SOAR optimizer in Python'
readme = "README.rst"
requires-python = ">=3.9,<3.12"
license = "MIT"
keywords = []
authors = [
  { name = "Tanmay Khandait", email = "tkhandai@asu.edu" },
  { name = "Quinn Thibeault", email = "qthibeau@asu.edu" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "numpy",
    "scipy",
    "numdifftools ~= 0.9.40",
    "pyswarms ~= 1.3.0",
    "pyswarm ~= 0.6",
    "scikit-optimize ~= 0.9.0",
    "deap ~= 1.3.3",
    "pymoo ~= 0.6.0",
    "polytope ~= 0.2.3",
    "Shapely ~= 1.8.2",
    "psy-taliro[rtamt] ~= 1.0.0",
]

[project.urls]
Documentation = "https://github.com/cpslab-asu/PySOAR-C#readme"
Issues = "https://github.com/cpslab-asu/PySOAR-C/issues"
Source = "https://github.com/cpslab-asu/PySOAR-C"

[tool.hatch.version]
path = "src/soar/__init__.py"

[tool.hatch.build.targets.sdist]
include = ["src/soar"]

[tool.hatch.build.targets.wheel]
packages = ["src/soar"]


[tool.hatch.envs.default]
dependencies = [
    "pytest",
]

[tool.hatch.envs.default.scripts]
tests = "pytest {args:tests}"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]

[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/pysoar tests}"

[tool.hatch.envs.all]
matrix = [
    { python = ["3.8", "3.9", "3.10", "3.11"] }
]

[tool.hatch.envs.lint]
detached = true
dependencies = [
    "ruff>=0.8",
]

[tool.hatch.envs.lint.scripts]
check = [
    "ruff check {args:src tests}",
    "ruff format --check {args:src tests}"
]
format = "ruff format {args:src tests}"

[tool.pyright]
include = ["src"]
stubPath = "src/stubs"

[tool.mypy]
mypy_path = "src/stubs"
files = ["src/**/*.py", "tests/*.py"]

[tool.ruff]
target-version = "py39"
line-length = 100
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
select = [
    "E4", "E7", "E9", "F", "C90",  # Default Flake8 lints
    "A",                           # Built-in shadowing lints
    "B",                           # Bugbear lints
    "I",                           # Isort lints
    "FURB",                        # Modern python lints
    "UP",                          # Upgrade lints
    "C4",                          # List comprehension lints
    "PL",                          # Pylint lints
    "PYI",                         # Stub file lints
    "RET501", "RET502", "RET504",  # Return value lints
    "TC",                          # Type-checking lints
    "N8",                          # Naming plugin
    "TD",                          # TODO plugin
    "TRY",                         # Error handling lints
    "FBT",                         # Boolean trap lints
    "SIM",                         # Simplification lints
    "PTH",                         # Pathlib migration lints
]

[tool.ruff.lint.per-file-ignores]
"src/stubs/**/*.pyi" = ["A002", "N801", "N803"]
