[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pysoar-c"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
keywords = []
authors = [
  { name = "Tanmay Khandait", email = "tkhandai@asu.edu"},
  { name = "Quinn Thibeault", email = "qthibeau@asu.edu" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "numpy",
    "numdifftools ~= 0.9.40",
    "pyswarms ~= 1.3",
    "pyswarm ~= 0.6",
    "scipy",
    "matplotlib ~= 3.5",
    "scikit-optimize ~= 0.9",
    "psy-taliro ~= 1.0",
    "coverage ~= 6.4",
    "jmetalpy ~= 1.5",
    "deap ~= 1.3",
    "pymoo ~= 0.6",
    "matlabengine",
]

[project.urls]
Documentation = "https://github.com/cpslab-asu/PySOAR-C#readme"
Issues = "https://github.com/cpslab-asu/PySOAR-C/issues"
Source = "https://github.com/cpslab-asu/PySOAR-C"

[tool.hatch.build.targets.wheel]
packages = ["src/soar"]

[tool.hatch.version]
path = "src/soar/__init__.py"

[tool.hatch.envs.default]
dependencies = [
    "ruff",
]

[tool.hatch.envs.default.scripts]
lint = "ruff check {args:src/soar test}"
format = "ruff format {args:src/soar test}"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]

[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/soar tests}"

[tool.hatch.envs.tests]
extra-dependencies = [
    "pytest",
]

[tool.hatch.envs.tests.scripts]
run = "pytest tests"
