from __future__ import annotations

class Kernel: ...
class ConstantKernel(Kernel): ...
class CompoundKernel(Kernel): ...
class PairwiseKernel(Kernel): ...
class WhiteKernel(Kernel): ...
class Matern(Kernel):
    def __init__(self, nu: float): ...
class RBF(Kernel): ...
