from __future__ import annotations

class Kernel: ...
class ConstantKernel(Kernel): ...
class CompoundKernel(Kernel): ...
class PairwiseKernel(Kernel): ...
class WhiteKernel(Kernel): ...
class Matern(Kernel): ...
class RBF(Kernel): ...
